[package]
name = "rust-remote-based-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql = { git = "https://github.com/libsql/libsql" }
# libsql = { path = "../../libsql/crates/core" }
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
